version: '3.0'

services:
  db:
    image: postgres:15
    container_name: db-store
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres123
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres -h 127.0.0.1" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-store
    ports:
      - "5173:80"
    depends_on:
      - app 
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - /etc/nginx/sites-available/lascovo.ru:/etc/nginx/conf.d/lascovo.ru.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./static:/var/www/static
    ports:
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app-store
    environment:
      - DB_NAME=postgres123
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres123
      - DB_PASS=postgres123

      - SMTP_PASSWORD=yemiewyefyxruwwj
      - SMTP_USER=maga2007.magomedov@yandex.ru
      - SMTP_PORT=587
      - SMTP_HOST=smtp.yandex.ru

      - SECRET_KEY=your-secret-key-change-in-production-4roads-2025
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=3

      - ADMIN_CHAT_ID=-1003670057573
      - BOT_TOKEN=7792052665:AAH2JOi1_cduXPhqjXY6hbMLBmCoWzb0aew

      - APP_NAME=lascovo-api
      - DEBUG=true
      - STATIC_URL=https://api.lascovo.ru/static/images
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,https://www.lascovo.ru,https://lascovo.ru
      - SITEMAP_PASSWORD=m_8jMpDsZ09yF1AphJnnEOg_zW0UOe4KXM4cvr_BkvY
      
      - MAX_IMAGE_SIZE_MB=10
      - WEBP_QUALITY=85
    depends_on:
      db: 
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static

networks:
  app-network:
    driver: bridge
